import '@/styles/globals.css'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Nassuel Personal Portfolio V2',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }: {Component: any, pageProps: any}) {
  return <Component {...pageProps} />
}